services:
  smtp-loadbalancer:
    container_name: smtp-loadbalancer
    image: ghcr.io/ovosimpatico/smtp-loadbalancer:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    volumes:
      # Config file
      - ./config.json:/app/config/config.json:ro
      # Logs
      - ./logs:/app/logs
      # Email queue DB
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - CONFIG_PATH=/app/config/config.json
    ports:
      - "2525:2525"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2525"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
